# Состояния диалога и общие константы бота.
STATE_REG_NAME = "REG_NAME"
STATE_REG_AGE = "REG_AGE"
STATE_REG_GENDER = "REG_GENDER"
STATE_REG_CITY = "REG_CITY"
STATE_REG_LOOKING = "REG_LOOKING"
STATE_GAMES = "STATE_GAMES"
STATE_ABOUT = "STATE_ABOUT"
STATE_PHOTO = "STATE_PHOTO"
STATE_PHOTO_MORE = "STATE_PHOTO_MORE"
STATE_PHOTO_APPEND = "STATE_PHOTO_APPEND"
STATE_REVIEW = "STATE_REVIEW"
STATE_EDIT_MENU = "STATE_EDIT_MENU"
STATE_BROWSE = "STATE_BROWSE"
STATE_INCOMING_LIKE = "STATE_INCOMING_LIKE"
STATE_LIKE_MESSAGE = "STATE_LIKE_MESSAGE"
STATE_REPORT_REASON = "STATE_REPORT_REASON"
STATE_DEACTIVATE_CONFIRM = "STATE_DEACTIVATE_CONFIRM"
STATE_RESET_CONFIRM = "STATE_RESET_CONFIRM"
VK_MESSAGE_MAX_LENGTH = 4096
ABOUT_MAX_LENGTH = 2000
REPORT_REASON_MAX_LENGTH = 500
LIKE_MESSAGE_MAX_LENGTH = 500
ACTION_DEBOUNCE_SECONDS = 0.5
from .texts import (
    GENDER_LABEL_FEMALE,
    GENDER_LABEL_MALE,
    LOOKING_LABEL_ANY,
    LOOKING_LABEL_FEMALE,
    LOOKING_LABEL_MALE,
    NO_GAMES_TEXT,
)

users = {}

GENDER_LABELS = {"male": GENDER_LABEL_MALE, "female": GENDER_LABEL_FEMALE}
LOOKING_LABELS = {"male": LOOKING_LABEL_MALE, "female": LOOKING_LABEL_FEMALE, "any": LOOKING_LABEL_ANY}
