EMOJI_CHECK = chr(0x2705)
EMOJI_CROSS = chr(0x274C)
EMOJI_LIKE = chr(0x2764) + chr(0xFE0F)
EMOJI_MESSAGE = chr(0x1F48C)
EMOJI_DISLIKE = chr(0x1F44E)
EMOJI_REPORT = chr(0x1F6A9)
EMOJI_GAMES = chr(0x1F3AE)
EMOJI_SMILE = chr(0x1F603)

BUTTON_START = "Начать"
BUTTON_GENDER_MALE = "Парень"
BUTTON_GENDER_FEMALE = "Девушка"
BUTTON_LOOKING_MALE = "Парня"
BUTTON_LOOKING_FEMALE = "Девушку"
BUTTON_LOOKING_ANY = "Без разницы"
BUTTON_PHOTO_DONE = "Это всё"
BUTTON_KEEP_CURRENT = "Оставить как есть"
BUTTON_REVIEW_BROWSE = "Да, смотреть анкеты"
BUTTON_EDIT_PROFILE = "🧑 Изменить инфо о себе"
BUTTON_EDIT_ABOUT = "📝 Изменить описание"
BUTTON_EDIT_GAMES = "🎮 Изменить игры"
BUTTON_EDIT_PHOTO = "📷 Изменить фото"
BUTTON_RESET = "Сбросить данные"
BUTTON_DEACTIVATE_PROFILE = "Отключить анкету"
BUTTON_EDIT_NAME = "Имя"
BUTTON_EDIT_AGE = "Возраст"
BUTTON_EDIT_GENDER = "Пол"
BUTTON_EDIT_LOOKING = "Кого ищу"
BUTTON_EDIT_CITY = "Город"
BUTTON_BACK = "Назад"
BUTTON_GAMES_DONE = "Готово"
BUTTON_BACK_TO_NEW = "Вернуться к новым анкетам"
BUTTON_BACK_TO_PREVIOUS = "Вернуться к предыдущей анкете"
BUTTON_MY_PROFILE = "Моя анкета"
BUTTON_REPORT = f"{EMOJI_REPORT} Пожаловаться"
BUTTON_BROWSE = "Смотреть анкеты"
BUTTON_CANCEL_REPORT = "Отменить жалобу"
BUTTON_BACK_FROM_MESSAGE = "Вернуться назад"
BUTTON_DEACTIVATE = "Отключить"

LABEL_TEST_BOT = "тестовый бот"
LABEL_THIS_PERSON = "Этот человек"
LABEL_MY_PROFILE_FALLBACK = "Твоя анкета"
LABEL_NO_NAME = "Без имени"
LABEL_NO_CITY = "Без города"
LABEL_GAMES_UNSPECIFIED = "не указаны"
LABEL_FRIEND = "друг"

NO_GAMES_TEXT = "играю в другие игры"
GENDER_LABEL_MALE = BUTTON_GENDER_MALE
GENDER_LABEL_FEMALE = BUTTON_GENDER_FEMALE
LOOKING_LABEL_MALE = BUTTON_LOOKING_MALE
LOOKING_LABEL_FEMALE = BUTTON_LOOKING_FEMALE
LOOKING_LABEL_ANY = BUTTON_LOOKING_ANY

MSG_GAMES_SUMMARY_PREFIX = "Твои игры: "
MSG_GAMES_PICKER = 'Выбери игры и нажми "Готово"'
MSG_PHOTOS_ENOUGH = "Фото уже достаточно"
MSG_ADD_ONE_PHOTO = "Добавь ещё 1 фото, если хочешь"
MSG_ADD_ONE_TWO_PHOTOS = "Добавь ещё 1-2 фото, если хочешь"
MSG_REVIEW_SUFFIX = "Всё верно?"
MSG_PROFILE_IN_HISTORY_LIKED = "Ты уже поставил лайк этой анкете, изменить оценку нельзя"
MSG_NO_PROFILES = "Анкет пока нет"
MSG_NO_HISTORY = "Больше просмотренных анкет нет."
MSG_NAME_PROMPT = "Как тебя зовут?"
MSG_AGE_PROMPT = "Сколько тебе лет?"
MSG_GENDER_PROMPT = "Ты кто?"
MSG_CITY_PROMPT = "Ты из какого города?"
MSG_LOOKING_PROMPT = "Кого ты ищешь?"
MSG_ABOUT_PROMPT = "Расскажи о себе"
MSG_ADD_PHOTO_PROMPT = "Добавь фото. Максимум - 3"
MSG_SEND_MESSAGE_PROMPT = "Напиши сообщение до 500 символов"
MSG_REPORT_REASON_PROMPT = "Опиши причину жалобы"
MSG_TEXT_500_ONLY = "Я принимаю только текст до 500 символов"
MSG_REPORT_SENT = "Жалоба отправлена"
MSG_TEXT_2000_ONLY = "Я принимаю только текст до 2000 символов"
MSG_PHOTOS_ONLY = "Я жду 1-3 фото. Я принимаю только фото :)"
MSG_PHOTOS_MAX = "В анкете может быть максимум 3 фото"
MSG_SAVE_ONLY_PHOTOS = "Я сохраняю только фото."
MSG_RESET_CONFIRM = "Это полностью очистит анкету и всю историю действий в боте. Подтверждаешь сброс?"
MSG_DEACTIVATE_CONFIRM = "Ты действительно хочешь отключить свою анкету?"
MSG_WHAT_TO_EDIT = "Что изменить"
MSG_ABOUT_EDIT_PROMPT = "Напиши о себе"
MSG_SEND_PHOTOS_PROMPT = "Пришли фото. Максимум - 3"
MSG_REVIEW_FALLBACK = "Выбери кнопку. Всё верно?"
MSG_EDIT_MENU_FALLBACK = "Выбери кнопку"
MSG_INVALID_NAME = "Как тебя зовут? Напиши корректно (текст до 50 символов)"
MSG_AGE_NUMBER = "Сколько тебе лет? Напиши число"
MSG_AGE_14PLUS = "Бот 14+. Сколько тебе лет?"
MSG_AGE_REAL = "Напиши реальный возраст. Сколько тебе лет?"
MSG_GENDER_BUTTON = "Ты кто? Выбери кнопку"
MSG_INVALID_CITY = "Ты из какого города? Напиши корректно (текст до 50 символов)"
MSG_LOOKING_BUTTON = "Кого ты ищешь? Выбери кнопку"
MSG_CHOOSE_GAMES_WITH_BUTTONS = "Выбери игры и нажми \"Готово\""
MSG_RETURNING = "С возвращением!"
MSG_CHOOSE_ACTION = "Выбери действие"
MSG_LIKE_LOCKED = "Лайк уже отправлен, изменить оценку нельзя. Можно пожаловаться, вернуться назад или к новым анкетам."
MSG_RESET_DONE = "Данные анкеты и история действий очищены. Можем пройти регистрацию заново."
MSG_CONSOLE_STARTED = "Бот запущен..."
MSG_CONSOLE_LONGPOLL_RECONNECT = "Long Poll переподключение после ошибки: "

TEMPLATE_PROFILE_TEXT = "{name}, {age}, {city}\n{emoji_games} {games_text}\n{about}"
TEMPLATE_GAMES_SUMMARY = "{prefix}{games_text}"
TEMPLATE_LIKE_NOTIFICATION = "{target_name}, твоя анкета кому-то понравилась! {emoji_smile}\n\n{liker_profile_text}"
TEMPLATE_OPTIONAL_MESSAGE = "\n\n{emoji_message}: {message}"
TEMPLATE_MATCH_MESSAGE = "{profile_text}\n\nЭто мэтч! {emoji_smile}\n{other_name} - {vk_link}"
TEMPLATE_REPORT_MESSAGE = (
    "{profile_text}\n\n"
    "Жалоба на анкету\n"
    "Кто пожаловался: {reporter_name}\n"
    "{reporter_link}\n"
    "На кого: {reported_name}\n"
    "{reported_link}\n\n"
    "Причина:\n{reason_text}"
)
MSG_BANNED = "Твоя анкета заблокирована за нарушение правил. Если считаешь это ошибкой, свяжись с администратором."
TEMPLATE_DONE_MESSAGE = "{name}, всё готово! Возвращайся :)"
